### ISSUE TITLE
[UI] - Build the navigation drawer component

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate-app#13]
## Acceptance Criteria

1. This navigation drawer component will compromise of all the categories alongside a lot of other todo features. The drawer on the mockups resembles a bare bones basic version. Maybe muiv5 offers more solution ? We should take some time to research.
2. It should not be collapsible unless viewing on form factor xs or below. We do not have that workflow yet.
3. The mockups does show icon, name, description but not much more is displayed. we should be able to display a lot of more information. lets make use of the space.
4. Users start with default certain categories ( this has not been finalized yet ). These categories do not cover the entire width of the navigation bar from top to bottom. We should be able to make the group of the list collapsible. This group is NOT CATEGORIES. This is the parent of the categories. For eg, A cup is an item. Storing it in pantry is a inventory item in pantry. User can categorize it as PANTRY. User can also group it as HOME or KITCHEN. The group here is like tag.
5. Users are able to edit tags. Users can create, update, view and delete tags. Tags are not archived. All items that were under a certain tag are simply removed from the tag if the tag is removed. Items are not affected.
6. Add icons for more visibility.

**Comment by mohit2530** [comment]
Completed this with previous pr.

**Comment by mohit2530** [comment]
![image](https://github.com/earmuff-jam/climate-app/assets/44540219/6a9b66fc-fad2-4624-ad8d-ed6f07d2c62e)
