### ISSUE TITLE
[UI] - Use storybook to design all components for jsx

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate-app#2]
## Acceptance Criteria

1. We need to be able to use storybook to design all components before we add data and logic to the components.
2. We should follow a structure to use components where redux store is not used and containers to support redux store usage.

**Comment by mohit2530** [comment]
The main undertaking from this ticket should be the ability to create components from storybook. the structure can be a tech debt but everyone here is familiar with the workflow so the process should not be that difficult.
