### ISSUE TITLE
[UI] - Build the layout for the landing page

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate-app#5]
# Acceptance Criteria

1. Build the landing page with storybook.
2. This ticket is geared to only designing and implementing the landing page without any data ( redux store ).
3. There are three main components - header with search bar, left drawer component, main section to show all the items and a right modal that opens to see detailed description of the items.
4. All of the items must have their own story book because we want a proper component layout system.

**Comment by mohit2530** [comment]
Completed issue in a different PR. 
![image](https://github.com/earmuff-jam/climate-app/assets/44540219/79103d65-bc93-4ca2-bfb3-c3f7f2986920)
